### ISSUE TITLE
Unknown fans

### ISSUE THREAD

**Issue by pittbull** [GMTrevis/Homeassistant-NodeRed-Systemair-VTR300#16]
Could you helpe me identify why these fans suddenly show up as unknown?

![image](https://github.com/GMTrevis/Homeassistant-NodeRed-Systemair-VTR300/assets/1532149/e93ba1a7-527f-46be-8963-36faf8fb3796)

**Comment by GMTrevis** [comment]
You have probably fixed this by now.
Anyway, i recall that i had to do a minor change after an update, i do not remember what i did, so i copy the code below.
The airflow is estimated in the "Calc. m3/t" node.

![image](https://github.com/GMTrevis/Homeassistant-NodeRed-Systemair-VTR300/assets/69414078/df0d19ce-8ab9-4777-afa4-c469c38f0f93)

![image](https://github.com/GMTrevis/Homeassistant-NodeRed-Systemair-VTR300/assets/69414078/6cfca771-e52c-4984-a27e-2f3481f0b5c0)

**Comment by pittbull** [comment]
Thanks
