### ISSUE TITLE
meta name issue (scalar)

### ISSUE THREAD

**Issue by dkjswart** [GMTrevis/Homeassistant-NodeRed-Systemair-VTR300#3]
It seems that I get error on the _meta name_ input in the yaml file. I have installed the dependencies in HACS as well as the customui.
![Untitled](https://user-images.githubusercontent.com/89411328/151756115-fd4c3b6e-640e-45c6-b3e6-3becd0ccbce5.png)

**Comment by GMTrevis** [comment]
> It seems that I get error on the _meta name_ input in the yaml file. I have installed the dependencies in HACS as well as the customui. ![Untitled](https://user-images.githubusercontent.com/89411328/151756115-fd4c3b6e-640e-45c6-b3e6-3becd0ccbce5.png)

I'm not familiar with this issue.
Sure you have named the Include section in "configuration.yaml" correct?

If you use the same config as mine you should have the following in configuration.yaml:
`sensor: !include_dir_merge_list sensors/`

and you should have a folder named "sensors" in the "config folder"
The "sensors_time_date_misc.yaml" file should be located in the "sensors" file.

![image](https://user-images.githubusercontent.com/69414078/152208727-26ae350a-d1e9-45d8-aab1-33f69a7a5f5f.png)

**Comment by ThermIQ** [comment]
Could this be an internationalization issue? I've had similar issues with 'åäö' when copying files from github to my HA. Try to ensure that all yaml files are UTF8 encoded and looks OK after downloading.

**Comment by GMTrevis** [comment]
> Could this be an internationalization issue? I've had similar issues with 'åäö' when copying files from github to my HA. Try to ensure that all yaml files are UTF8 encoded and looks OK after downloading.

You may be right, did spotchecks and my files are in UTF8 format, checked in Notepad++
Maybe the format can be changed when downloaded and altered in regular notepad? or local default format is different, im not sure...
![image](https://user-images.githubusercontent.com/69414078/154836713-e4b3132e-1cb1-4834-9ecf-4deca6dcec85.png)

**Comment by GMTrevis** [comment]
Closing this as there has been no further issues reported.
